### ISSUE TITLE
Gpx and Kml import broke during Typescript rewrite (v2.3.0)  

### ISSUE THREAD

**Issue by jaybo** [jaybo/deepzoom-blog#4]
Silently fails with console error:
```
TypeError: DZ.dzStore.userConfirmAsync is not a function
    at Ye.<anonymous> (896.bc783183.js:1:77719)
    at Generator.next (<anonymous>)
    at r (896.bc783183.js:1:72550)
```

**Comment by jaybo** [comment]
Fixed in v2.3.20
